### PR TITLE
Adds CLI args and option to launch profiles from CLI without constructing forms

### LINKED ISSUE #53: command line argument to launch a specific account, then close

### PR DESCRIPTION
**Pull request by box-cs**
Hey, I wanted to help with something with gw.

This would close #53

---

Here's how you'd launch multiple profiles, if the profiles don't exist a message box will show.

In a `.bat` file:
```batch
@echo off
START /B "" "C:\<path/to/gwlauncher>\GW Launcher.exe" profiles 0,1,2
```

Code stuff:
I moved the account launching into a function and just reused it while trying to make as little changes to the code as I could. Accounts are loaded a bit earlier, since we need them to launch profiles.

### CODE REVIEW

**Comment by DubbleClick** [comment]
In general, contributions are very welcome! Right now this PR doesn't do anything with the parsed cmd args, though. When you add functionality, such as launching a specific account without showing the gw launcher window, I'm happy to merge it. Keep the mutex check in mind.

**Comment by box-cs** [comment]
>Right now this PR doesn't do anything with the parsed cmd args

You can test this pr with a `batch` script with command line args flags:
```batch
START /B "" "C:\<path/to/gwlauncher>\x86\Debug\net6.0-windows\GW Launcher.exe" profiles 0,1,2
```

**Comment by DubbleClick** [comment]
I see, you construct needtolaunch with the account indexes. I'm not a huge fan of this, the cmd line args should be usable with gw launcher already being open - and using command line args to specify what to launch should not open the gui application. They should be two separate things.

**Comment by box-cs** [comment]
> I see, you construct needtolaunch with the account indexes. I'm not a huge fan of this, the cmd line args should be usable with gw launcher already being open - and using command line args to specify what to launch should not open the gui application. They should be two separate things.

Sounds good

**Comment by DubbleClick** [comment]
The approach you just implemented won't work, you need to write a function that launches the accounts without running into the gw launcher mutex or creating the form at all.

**Comment by box-cs** [comment]
> The approach you just implemented won't work, you need to write a function that launches the accounts without running into the gw launcher mutex or creating the form at all. But keep in mind that you will have to check whether an instance from the launched paths is already open.

Yep, working on that

**Pull request closed without merging**
